workoutApp/workoutApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("workoutApp.common.urls")),
    path('workout/', include("workoutApp.workouts.urls")),
    path('nutrition/', include("workoutApp.nutrition.urls")),
    path('accounts/', include("workoutApp.accounts.urls")),
    path('complexes/', include("workoutApp.complexes.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workoutApp/workoutApp/users/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from workoutApp.common_utils.validators import validate_filesize
from workoutApp.workouts.models import Exercise
from decimal import Decimal


# User = get_user_model()
class CustomUser(AbstractUser):

    first_name = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        help_text="Enter your first name (not required).."
    )

    last_name = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        help_text="Enter your last name (not required).."
    )

    email = models.EmailField(
        max_length=30,
        unique=True,
        error_messages={
            "unique": "Choose different e-mail, please.", }
    )

    class Meta:
        permissions = [
            ('can_view_management_profile', 'Can view Management profile'),
        ]


class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='profile')
    profile_picture = models.ImageField(
        upload_to="profiles/profile_picture",
        default='default_profile.jpg',
        validators=[
            validate_filesize,
        ],
        help_text="Upload your profile picture..",
        null=True,
    )

    trainer = models.BooleanField(default=False)
    is_public = models.BooleanField(default=False)


class RepMax(models.Model):
    user = models.ForeignKey(
        'users.CustomUser',
        on_delete=models.CASCADE,
        related_name='rep_maxes'
    )

    exercise = models.ForeignKey(
        Exercise,
        on_delete=models.CASCADE,
        related_name='rep_maxes'
    )

    max_weight = models.DecimalField(
        decimal_places=2,
        max_digits=5,
        # validators=[MinValueValidator(0)],
    )

    reps = models.PositiveIntegerField(
        # validators=[MinValueValidator(1)]
    )

    calculated_rm = models.DecimalField(
        decimal_places=2,
        max_digits=5
    )

    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        print("Save of RM")
        if self.max_weight and self.reps:
            self.calculated_rm = self.max_weight * (1 + Decimal(0.0333) * self.reps)
            print(f"{self.user.username}'s RepMax for {self.exercise.name}: {self.calculated_rm} kg")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.username}'s RepMax for {self.exercise.name}: {self.calculated_rm} kg"

workoutApp/workoutApp/workouts/models.py
from django.core.validators import MinValueValidator, MinLengthValidator
from django.db import models
from django.db.models import Max
from django.http import request
from django.utils import timezone

from workoutApp.common_utils.mixins import AutoIncrementOrder
from workoutApp.common_utils.validators import name_validator, date_today_validator
from workoutApp.common_utils.workout_choices import WorkoutType, ExrxCategory, ExrxType


# Create your models here.
class WorkoutBase(models.Model):

    workout_type = models.CharField(
        max_length=30,
        choices=WorkoutType.choices,
        )

    created_at = models.DateTimeField(
        auto_now_add=True,
        )

    updated_at = models.DateTimeField(
        auto_now=True
        )
    # exercise = models.ManyToManyField('Exercise', blank=True)

    class Meta:
        abstract = True


class Workout(WorkoutBase):
    user = models.ForeignKey(
        'accounts.CustomUser',
        on_delete=models.CASCADE,
        related_name='workouts'
        )

    workout_date = models.DateField(
        blank=True,
        null=True,
        default=timezone.now,
        validators=[date_today_validator],
        )

    def save(self, *args, **kwargs):
        if not self.user:
            self.user = request.user
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.workout_type}"

    def get_tot_volume(self):
        total = sum(xrx.reps * xrx.weight for xrx in self.sets.all())
        return total

    def get_exercises(self):
        # return  ", ".join([p.exercise.name for p in self.sets.all()])

        return [p.exercise.name for p in self.sets.all()]

    def get_all_sets_reps(self):
        listed = []
        for xrx in self.sets.all():

            listed.append(f"{xrx.order}{xrx.reps} - {xrx.weight}")
        return ", ".join(listed)

    def get_all(self):
        all_info = {}

        for xrx in self.sets.all():
            exercise = xrx.exercise.name
            info = f"{xrx.reps}x{xrx.weight:.0f}"

            if exercise not in all_info:
                all_info[exercise] = []
            all_info[exercise].append(info)

        return all_info


class WorkoutTemplate(WorkoutBase):
    name = models.CharField(max_length=100)
    description = models.TextField(
        blank=True,
        null=True,
        )


class ExerciseCategory(models.Model):
    category = models.CharField(
        max_length=100,
        choices=ExrxCategory.choices,
        )

    def __str__(self):
        return self.category


class WorkoutSet(models.Model):
    workout = models.ForeignKey(
        Workout,
        on_delete=models.CASCADE,
        related_name='sets',
        )

    exercise = models.ForeignKey(
        'Exercise',
        on_delete=models.CASCADE,
        related_name='workout_sets',
        )

    reps = models.PositiveIntegerField(
                    validators=[MinValueValidator(1)],
                    default=0,
                    )

    weight = models.DecimalField(
        decimal_places=2,
        max_digits=5,
        validators=[MinValueValidator(0)], default=0,
        )

    order = models.PositiveIntegerField(
        default=0,
        )

    # Ordering the sets of the exercises.
    def save(self, *args, **kwargs):
        if self.weight > 0 and self.reps > 0:
            if self.order == 0 or not self.order:

                max_order = WorkoutSet.objects.filter(
                    workout=self.workout,
                    exercise=self.exercise).aggregate(Max('order'))[
                    'order__max']
                self.order = (max_order or 0) + 1
            super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.exercise.name} - {self.reps} reps : {self.weight} kg"


class Exercise(models.Model):

    MIN_LEN_NAME = 3

    name = models.CharField(
        max_length=100,
        validators=[MinLengthValidator(MIN_LEN_NAME), name_validator],
        null=True,
        blank=True,
        )

    category = models.CharField(
        max_length=100,
        choices=ExrxCategory.choices)

    type = models.CharField(
        max_length=100,
        choices=ExrxType.choices)

    def __str__(self):
        return self.name

workoutApp/workoutApp/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from workoutApp.common_utils.workout_choices import ExrxCategory, ExrxType
from workoutApp.users.models import CustomUser, UserProfile
from workoutApp.workouts.models import Exercise


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=20, required=False)
    last_name = forms.CharField(max_length=20, required=False)
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'placeholder': '(leave blank to keep current)',
                   'autocomplete': 'new-password'}),
        label='Change your password (Leave blank to keep the current password)',
        required=False
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_picture', ]

        profile_picture = forms.ImageField(required=False)


class ExerciseFilterForm(forms.Form):
    EXERCISE_CATEGORY_CHOICES = ExrxCategory.choices
    EXERCISE_TYPE_CHOICES = ExrxType.choices

    exercise_category = forms.ChoiceField(
        choices=[('', 'All Categories')] + list(EXERCISE_CATEGORY_CHOICES),
        required=False,
        label="exercise_category",
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    exercise_type = forms.ChoiceField(
        choices=[('', 'All Types')] + list(EXERCISE_TYPE_CHOICES),
        required=False,
        label="exercise_type",
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    exercise_names = forms.ModelChoiceField(
        queryset=Exercise.objects.all(),
        required=False,
        empty_label="Select Exercise",
        label="Exercise",
        widget=forms.Select(attrs={'class': 'exercise-dropdown'})
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user:
            exercises_for_user = Exercise.objects.filter(repmax__user=user).distinct()
            self.fields['exercise_names'].queryset = exercises_for_user

workoutApp/workoutApp/users/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.db.models import Count
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, update_session_auth_hash
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView
from .forms import CustomLoginForm, CustomUserCreationForm, CustomUserChangeForm, UserProfileForm, ExerciseFilterForm
from .models import CustomUser, RepMax, UserProfile
from .permissions import IsStaffOrOwner
from ..workouts.models import Workout


def custom_login_view(request):
    if request.method == 'POST':
        form = CustomLoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)

            next_url = request.GET.get('next', '/')
            # print(f"REDIRECT =>>>>>>>>>>>> {next_url}")
            return redirect(next_url)
    else:
        form = CustomLoginForm()

    context = {'form': form}

    return render(request, 'users/login.html', context)


class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)

        return redirect(self.success_url)


def custom_logout(request):
    if request.user.is_authenticated:
        logout(request)
    else:
        return HttpResponseRedirect('/')

    return redirect('index')


class CustomUserEditView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'users/edit_profile.html'
    success_url = reverse_lazy('user-profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Pass the UserProfileForm with the user's profile instance
        context['profile_form'] = UserProfileForm()
        return context

    def form_valid(self, form):
        profile_form = UserProfileForm(self.request.POST, self.request.FILES, instance=self.request.user.profile)

        if profile_form.is_valid():
            profile_form.save()

        password = form.cleaned_data.get('password')
        if password:
            self.object.set_password(password)

        self.object.save()

        if password:
            update_session_auth_hash(self.request, self.object)

        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)


@login_required
def user_profile_view(request):
    user = request.user
    profile_picture = user.profile.profile_picture if user.profile else None

    context = {
        'user': user,
        'profile_picture': profile_picture
    }
    return render(request, 'users/profile.html', context)


def staff_required(view_func):
    return user_passes_test(lambda u: u.is_staff)(view_func)


@staff_required
def view_all_profile(request):
    users = CustomUser.objects.annotate(workout_count=Count('workouts'))
    # users = CustomUser.objects.all()
    context = {'users': users}

    return render(request, 'users/manage_all_profiles.html', context)


# view_profile - included custom permission
def view_profile(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)

    if not IsStaffOrOwner.has_permission(request.user, pk):
        raise PermissionDenied("You do not have permission to view this profile.")

    workout_count = Workout.objects.filter(user=user).count()
    profile_picture = user.profile.profile_picture if user.profile else None

    context = {
        'user': user,
        'profile_picture': profile_picture,
        'workout_count': workout_count,
    }

    return render(request, 'users/manage_profile.html', context)


@staff_required
def delete_profile(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)

    if user == request.user:
        messages.error(request, "You cannot delete your own profile.")
        return redirect('all-profiles')

    user.delete()
    messages.success(request, f"The profile of {user.username} has been deleted.")

    return redirect('all-profiles')


class PublicUserProfileListView(ListView):
    model = UserProfile
    template_name = 'users/public_profiles_list.html'  # Adjust path if needed
    context_object_name = 'user_profiles'
    paginate_by = 5

    def get_queryset(self):
        return UserProfile.objects.filter(is_public=True)


class RepMaxStatusView(LoginRequiredMixin, ListView):
    model = RepMax
    template_name = 'users/repmax_details.html'
    context_object_name = 'repmaxes'
    paginate_by = 3

    def get_queryset(self):
        user = get_object_or_404(CustomUser, pk=self.kwargs['pk'])
        user_profile = get_object_or_404(UserProfile, user=user)

        if user != self.request.user and not user_profile.is_public:
            raise Http404("This profile is private.")

        queryset = RepMax.objects.filter(user=user).order_by("-max_weight", "-reps")

        form = ExerciseFilterForm(self.request.GET)
        if form.is_valid():
            category = form.cleaned_data.get('exercise_category')
            exercise_type = form.cleaned_data.get('exercise_type')
            exercise_name = form.cleaned_data.get('exercise_names')

            if category:
                queryset = queryset.filter(exercise__category=category)

            if exercise_type:
                queryset = queryset.filter(exercise__type=exercise_type)

            if exercise_name:
                queryset = queryset.filter(exercise__name=exercise_name)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['filter_form'] = ExerciseFilterForm(self.request.GET)

        return context

workoutApp/templates/users/edit_profile.html
{%  extends 'common/base_template.html' %}
{%  load static %}
{% load crispy_forms_filters %}

{%  block content %}

     <section class="what_we_do_section layout_padding" style="background-color: #343a40; color: #f8f9fa;">
            <section class="container" style="width: 70%; padding-bottom: 5em">
                 <div class="row justify-content-center">
                    <div class="col-8">
                        <h1 class="mt-2"> <h2>Edit your information</h2></h1>

                        <hr class="mt-0 mb-4">
                              <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form|crispy }}

                                 <p><strong>Profile Picture:</strong><br> <img src="{% if user.profile.profile_picture  %}{{ user.profile.profile_picture.url }}{% else %}{% static 'images/default_profile.jpg' %}{% endif %}" alt="Profile Picture" width="100"></p>
                                  {{ profile_form|crispy }}


                                <button type="submit" class="btn btn-primary">Save</button>
                              </form>

                    </hr>
                    </div>
                 </div>
         </section>
    </section>


{% endblock %}

workoutApp/templates/users/login.html
{% extends 'common/base_template.html' %}

{% block content %}
    <section class="login-section" style="background-color: #f8f9fa; padding: 40px 0;">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6">
                    <!-- form-card -->
                    <div class="card">
                        <div class="card-header text-center">
                            <h4>Login</h4>
                        </div>
                        <div class="card-body">
                            <!-- Form -->
                            <form method="POST">
                                {% csrf_token %}

                                <!-- Form fields -->
                                <div class="form-group">
                                    <label for="{{ form.username.id_for_label }}">Username</label>
                                    {{ form.username }}
                                </div>

                                <div class="form-group">
                                    <label for="{{ form.password.id_for_label }}">Password</label>
                                    {{ form.password }}
                                </div>

                                <button type="submit" class="btn btn-primary btn-block">Login</button>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            {% if next %}
                                <p>You were redirected here from <strong>{{ next }}</strong></p>
                            {% endif %}
                            <p>Don't have an account? <a href="{% url 'register' %}">Sign up</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

workoutApp/templates/users/manage_all_profiles.html
{%  extends 'common/base_template.html' %}
{% load static %}



{% block content %}
  <h2 class="text-center mb-4">All User Profiles</h2>

 {% include 'users/management_sticky_warning.html' %}

    <!-- Profiles List -->
    <div class="row">
      {% for user in users %}
        <div class="col-md-4 mb-4">
          <div class="card" style="background-color: #f8f9fa; border: 1px solid #ced4da;">
            <div class="card-body">
              <h5 class="card-title text-dark">{{ user.username }}</h5>
              <p class="card-text">
                <strong>First Name:</strong> {{ user.first_name|default:"Not presented" }} <br>
                <strong>Last Name:</strong> {{ user.last_name|default:"Not presented" }} <br>
                <strong>Email:</strong> {{ user.email }}
                    <p><strong>Workouts:</strong> {{ user.workout_count }} workouts</p>
              </p>

              <a href="{% url 'view-profile' pk=user.pk %}" class="btn btn-primary btn-sm">View Profile</a>
              <a href="{% url 'delete-profile' pk=user.pk %}" class="btn btn-danger btn-sm ml-2" onclick="return confirm('Are you sure you want to delete this profile?');">Delete</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

workoutApp/templates/users/manage_profile.html
{%  extends 'common/base_template.html' %}



{% block content %}

    {% include 'users/management_sticky_warning.html' %}


 <div class="card" style="background-color: #f8f9fa; border: 1px solid #ced4da;">
    <h2 class="text-center">Profile of {{ user.username }}</h2>

    <p><strong>First Name:</strong> {{ user.first_name|default:"Not presented" }}</p>
    <p><strong>Last Name:</strong> {{ user.last_name|default:"Not presented" }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
     <p><strong>Workouts:</strong> {{ workout_count}}


    <p><strong>Profile Picture:</strong><br>
      <img src="{% if profile_picture  %}{{ profile_picture.url }}{% else %}{{ MEDIA_URL }}profiles/default.jpg{% endif %}" alt="Profile Picture" width="100">
    </p>
         <br>


    <a href="{% url 'delete-profile' pk=user.pk %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this profile?');">Delete Profile</a>
  </div>
  </div>

{% endblock %}

workoutApp/templates/users/management_sticky_warning.html
  <div class="container">
    <div class="alert alert-warning alert-dismissible fade show text-center sticky-alert" role="alert">
      <strong>Attention Staff Members!</strong> Please be responsible when managing user profiles. Deleting profiles cannot be undone.
        <br>
        <a href="{% url 'index' %}" class="btn btn-success">Go back to index</a>

    </div>

workoutApp/templates/users/profile.html
{%  extends 'common/base_template.html' %}
{% load static %}
{% load  custom_filters %}
{% load crispy_forms_field %}



{% block content %}


    <section class="what_we_do_section layout_padding" style="background-color: #343a40; color: #f8f9fa;">
            <section class="container" style="width: 70%; padding-bottom: 5em">
                 <div class="row justify-content-center">
                    <div class="col-8">
                        <h1 class="mt-2">  <h2>Welcome, {{ user.username }}!</h2></h1>
                    <hr class="mt-0 mb-4">




      <p><strong>First Name:</strong> {{ user.first_name|default_if_empty:"No first name provided" }}</p>
      <p><strong>Last Name:</strong> {{ user.last_name|default_if_empty:"No last name provided"  }}</p>
      <p><strong>Email:</strong> {{ user.email }}</p>
                        <p><strong>Public Profile:</strong> {{ user.profile.is_public|yesno:"Yes,No" }}</p>

{#      <p><strong>Trainer:</strong> {% if user.trainer %}Yes{% else %}No{% endif %}</p>#}


                       <p><strong>Profile Picture:</strong><br> <img src="{% if user.profile.profile_picture  %}{{ user.profile.profile_picture.url }}{% else %}{% static 'images/default_profile.jpg' %}{% endif %}" alt="Profile Picture" width="100"></p>

{#  {% if user.profile_picture %}#}
{#    <p><strong>Profile Picture:</strong><br><img src="{{ user.profile_picture.url }}" alt="Profile Picture" width="200"></p>#}
{#  {% else %}#}
{#    <p><strong>Profile Picture:</strong><br><img src="{%  staticfiles 'profiles/de' %}" alt="Profile Picture" width="200"></p>#}
{#  {% endif %}#}

  <a href="{% url 'edit-profile' %}" class="btn btn-primary">Edit Profile</a>
                        <a href="{% url 'logout' %}" class="btn btn-secondary">Logout</a>


                     </hr>
                    </div>
                 </div>
         </section>
    </section>


{%  endblock %}

workoutApp/templates/users/register.html
{%  extends 'common/base_template.html' %}
{% load static %}
{% load crispy_forms_filters %}




{%  block content %}

    <section class="what_we_do_section layout_padding" style="background-color: #343a40; color: #f8f9fa;">
            <section class="container" style="width: 70%; padding-bottom: 5em">
                 <div class="row justify-content-center">
                    <div class="col-8">
                        <h1 class="mt-2"> <h2>Create a New Account</h2></h1>

                        <hr class="mt-0 mb-4">
                              <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-primary">Register</button>
                              </form>
                    </hr>
                    </div>
                 </div>
         </section>
    </section>
{%  endblock %}

workoutApp/templates/users/repmax_details.html
{% extends 'common/base_template.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
 <div class="container mt-5">
     <!-- Filter form -->
    <div class="mb-4">
        <h4 class="mb-3 text-white">Filter RepMax Records</h4>
        <form method="get" class="filter-form">
              <div class="row">

                <div class="col-md-3 col-sm-6 mb-2">
                    {{ filter_form.exercise_category }}
                </div>


                <div class="col-md-3 col-sm-6 mb-2">
                    {{ filter_form.exercise_type }}
                </div>


                <div class="col-md-3 col-sm-6 mb-2">
                    {{ filter_form.exercise_names }}
                </div>


                <div class="col-md-3 col-sm-6 mb-2">
                    <button type="submit" class="btn btn-primary btn-block">Apply Filters</button>
                </div>
            </div>
        </form>
    </div>


    <h4 class="mb-4 text-white">RepMax Status</h4>


    <div class="row">
        {% for repmax in repmaxes %}
            <div class="col-md-4 mb-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <h5 class="card-title">{{ repmax.exercise.name }}</h5>
                            <div class="badge badge-info badge-box">{{ repmax.max_weight }} kg</div>
                        </div>
                        <p class="mb-1"><strong>Reps:</strong> {{ repmax.reps }}</p>
                        <p class="mb-1"><strong>Date:</strong> {{ repmax.created_at }}</p>

                         <h6 class="mt-3">Workouts with this RepMax:</h6>
                        <ul class="list-group list-group-flush">
                            {% for workout_set in repmax.exercise.workout_sets.all %}
                                {% if workout_set.weight == repmax.max_weight and workout_set.reps == repmax.reps %}
                                    <li class="list-group-item py-2">
                                        <p class="mb-1"><strong>Workout Date:</strong> {{ workout_set.workout.workout_date }}</p>
                                        <p class="mb-1"><strong>Workout Type:</strong> {{ workout_set.workout.workout_type }}</p>
                                        <a href="{% url 'workout_detail' workout_set.workout.id %}" class="btn btn-link p-0">View Workout</a>
                                    </li>
                                {% endif %}
                            {% empty %}
                                <li class="list-group-item py-2">
                                    <p class="mb-0 text-white">No workouts found for this exercise.</p>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-12">
                <p class="text-center text-white">No rep max records found with the applied filters.</p>
            </div>
        {% endfor %}
    </div>

    <!-- Pagination -->
  <div class="d-flex justify-content-center mt-4">
                <nav>
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link" aria-hidden="true">&laquo;</span>
                            </li>
                        {% endif %}

                        {% for num in page_obj.paginator.page_range %}
                            <li class="page-item {% if num == page_obj.number %}active{% endif %}">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link" aria-hidden="true">&raquo;</span>
                            </li>
                        {% endif %}
                    </ul>

                </nav>
            </div>
    </div>

</div>
{% endblock %}